// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import ToastController from "./toast_controller.js"
application.register("toast", ToastController)
