# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable


Bundler/OrderedGems:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# 一行の長さは120字まで。コメントは制限しない
Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - '\A#.+'
  Exclude:
    - "config/initializers/*"

# メソッドチェーンのインデントは自分で調整する
Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  # RSpecのchange { object.attribute }は許可する
  IgnoredMethods: [change]

Lint/EmptyBlock:
  Exclude:
    - "spec/models/**/*"
    - "app/controllers/user_hands_controller.rb"
    - "app/controllers/user_supports_controller.rb"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "app/models/game.rb"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/development.rb"

Metrics/ClassLength:
  Max: 150

# メソッドの行数を20行までにする
Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - "app/helpers/application_helper.rb"

Rails/HasManyOrHasOneDependent:
  Exclude:
    - "app/models/character.rb"

Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma