databases:
  - name: old_janken_production
    databaseName: old_janken_production
    user: old_janken_production_user
    region: singapore

services:
  - type: redis
    name: old_janken_production
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu
  - type: web
    name: old-janken
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: old_janken_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: old_janken_production
          property: connectionString