default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: old_janken_development
  username: utsumiwataru
  password:
  host: localhost

test:
  <<: *default
  database: old_janken_test

production:
  <<: *default
  database: old_janken_production
  username: old_janken_production_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
