default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: old_janken_development
  username: utsumiwataru
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: old_janken_test
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  pool: 5

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV['MAX_CONNECTION_POOL'] || 5 %>
