default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: old_janken_development
  username: utsumiwataru
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: old_janken_test
  port: 5432

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['HOSTNAME'] %>
  port: <%= ENV['PORT'] %>
  pool: <%= ENV['MAX_CONNECTION_POOL'] || 5 %>
