default: &default
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: old_janken_development
  username: pguser
  password: passwor

test:
  <<: *default
  database: old_janken_test
  username: pguser
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>